name: Documentation Check

on:
  push:
    branches:
      - main
      - develop
    paths:
      - '**.md'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - '**.md'
  workflow_dispatch:

jobs:
  markdown-lint:
    name: Markdown Linting
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Markdown Lint
        uses: articulate/actions-markdownlint@v1
        with:
          config: .markdownlint.json
          files: '**/*.md'
          ignore: node_modules
        continue-on-error: true

      - name: Check for broken links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.markdown-link-check.json'
        continue-on-error: true

  spell-check:
    name: Spell Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check spelling
        uses: rojopolis/spellcheck-github-actions@0.53.0
        with:
          config_path: .spellcheck.yml
        continue-on-error: true
